// Generated by start-school-center.bat.
window.SCHOOL_CENTER_CONFIG = {"mainUrl":"https://conditions-backed-cloudy-writes.trycloudflare.com","minecraftUrl":"https://ballet-conventional-towns-promptly.trycloudflare.com","generatedAt":"2026-08-29T23:42:43.220Z"};
