/* Chalkle Sites. The full list lives in your saved library - edit it any time
   from the Admin panel (Settings → Admin, code: jamesypoo). Kept alphabetically
   sorted; numbered groups read in numeric order (1, 2, 3, …). */

window.ChalkSites = [
  { title: "Arctic Mirror 1", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-1.svg", thumb: "/assets/games/arctic-1.jpg", category: "Arctic" , directOnly: true },
  { title: "Arctic Mirror 2", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-2.svg", thumb: "/assets/games/arctic-2.jpg", category: "Arctic" , directOnly: true },
  { title: "Arctic Mirror 3", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-3.svg", thumb: "/assets/games/arctic-3.jpg", category: "Arctic" , directOnly: true },
  { title: "Arctic Mirror 4", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-4.svg", thumb: "/assets/games/arctic-4.jpg", category: "Arctic" , directOnly: true },
  { title: "Arctic Mirror 5", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-5.svg", thumb: "/assets/games/arctic-5.jpg", category: "Arctic" , directOnly: true },
  { title: "Arctic Mirror 6", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-6.svg", thumb: "/assets/games/arctic-6.jpg", category: "Arctic" , directOnly: true },
  { title: "Arctic Mirror 7", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-7.svg", thumb: "/assets/games/arctic-7.jpg", category: "Arctic" , directOnly: true },
  { title: "Arctic Mirror 8", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-8.svg", thumb: "/assets/games/arctic-8.jpg", category: "Arctic" , directOnly: true },
  { title: "Arctic Mirror 9", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-9.svg", thumb: "/assets/games/arctic-9.jpg", category: "Arctic" , directOnly: true },
  { title: "Arctic Mirror 10", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/articsvg-auto-1@main/articsvg-10.svg", thumb: "/assets/games/arctic-10.jpg", category: "Arctic" , directOnly: true },
  { title: "Bull 33", url: "https://s3.dualstack.us-east-1.amazonaws.com/rahisbullsgoat/index.html", thumb: "/assets/games/t_bf72b98f28.jpg", category: "Games" },
  { title: "Cherri Mirror 1", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25001.svg", thumb: "/assets/games/cherri-1.jpg", category: "Cherri" , directOnly: true },
  { title: "Cherri Mirror 2", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25002.svg", thumb: "/assets/games/cherri-2.jpg", category: "Cherri" , directOnly: true },
  { title: "Cherri Mirror 3", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25003.svg", thumb: "/assets/games/cherri-3.jpg", category: "Cherri" , directOnly: true },
  { title: "Cherri Mirror 4", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25004.svg", thumb: "/assets/games/cherri-4.jpg", category: "Cherri" , directOnly: true },
  { title: "Cherri Mirror 5", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25005.svg", thumb: "/assets/games/cherri-5.jpg", category: "Cherri" , directOnly: true },
  { title: "Cherri Mirror 6", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25006.svg", thumb: "/assets/games/cherri-6.jpg", category: "Cherri" , directOnly: true },
  { title: "Cherri Mirror 7", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25007.svg", thumb: "/assets/games/cherri-7.jpg", category: "Cherri" , directOnly: true },
  { title: "Cherri Mirror 8", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25008.svg", thumb: "/assets/games/cherri-8.jpg", category: "Cherri" , directOnly: true },
  { title: "Cherri Mirror 9", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25009.svg", thumb: "/assets/games/cherri-9.jpg", category: "Cherri" , directOnly: true },
  { title: "Cherri Mirror 10", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/cherribydono-auto-25@main/cherribydono-25010.svg", thumb: "/assets/games/cherri-10.jpg", category: "Cherri" , directOnly: true },
  { title: "Cinder Cloud", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/cloudeducation-auto-1@main/cloudeducation-1.svg", thumb: "/assets/games/t_f1e5e746b5.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 1", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-1.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 2", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-2.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 3", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-3.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 4", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-4.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 5", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-5.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 6", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-6.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 7", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-7.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 8", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-8.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 9", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-9.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Cloudmoon 10", url: "https://fastly.jsdelivr.net/gh/Mtreasur0133-bit/realcloudmooneducation-auto-1@main/realcloudmooneducation-10.svg", thumb: "/assets/games/t_d58780fc4f.jpg", category: "Cloudmoon" , directOnly: true },
  { title: "Duck Math", url: "https://s3.us-east-2.amazonaws.com/mini.worthy/fungames+.svg", thumb: "/assets/games/t_a513b5bf82.jpg", category: "Games" },
  { title: "EzClassWork 1", url: "https://ezclasswork.com/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 2", url: "https://classroom15x.net/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 3", url: "https://classroom20x.net/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 4", url: "https://classroom10x.io/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 5", url: "https://pizzaedition.top/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 6", url: "https://pizzaeditiongames.io/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 7", url: "https://classroomunblockedgames.com/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 8", url: "https://ubg98.io/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 9", url: "https://unblocked-games.live/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 10", url: "https://unblockedgames66.school/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 11", url: "https://ubg911.net/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "EzClassWork 12", url: "https://catclass.net/", thumb: "/assets/games/t_37b3e88db4.jpg", category: "Unblocked" },
  { title: "Frosted", url: "https://fabbyscience.noordware.com/", thumb: "/assets/games/frosted.jpg", category: "Unblocked" },
  { title: "GNMath 1", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-1.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "GNMath 2", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-2.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "GNMath 3", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-3.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "GNMath 4", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-4.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "GNMath 5", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-5.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "GNMath 6", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-6.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "GNMath 7", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-7.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "GNMath 8", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-8.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "GNMath 9", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-9.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "GNMath 10", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/gnmath-auto-1@main/gnmath-10.svg", thumb: "/assets/games/t_139aa7085a.jpg", category: "GNMath" , directOnly: true },
  { title: "Imposter V2", url: "https://iteom.inspiration-partners.pl/", thumb: "/assets/games/t_af5362c56d.jpg", category: "Games" },
  { title: "Kiwi 1", url: "https://kahoot.cc/", thumb: "/assets/games/kiwi1.jpg", category: "Unblocked" },
  { title: "Kiwi 2", url: "https://www.classlink.online/", thumb: "/assets/games/kiwi2.jpg", category: "Unblocked" },
  { title: "Lucide", url: "https://mathassets.s3.amazonaws.com/index.html", thumb: "/assets/games/t_5cf6ecea32.jpg", category: "Games" },
  { title: "Mizu", url: "https://studyhall.gr.al/", thumb: "/assets/games/t_8eba218f46.jpg", category: "Games" },
  { title: "Nexora", url: "https://notepad20-a-ssl-fastly-net.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en", thumb: "/assets/games/t_429c2eaa6b.jpg", category: "Games" },
  { title: "Noahs Tutoring", url: "https://script.google.com/a/macros/students.wcpss.net/s/AKfycbz_3CKzRKXyisc_WYcOIG6adYY2QUTS13-jO0XA70aPzmiNz23XNHGaU9LYBgRs8iZq/exec?url=https%3A%2F%2Foriginfastly.jsdelivr.net%2Fgh%2FNoahsAmazingTutoringHelp%2Freimagined-octo-winner%40main%2Fblahblahblah.html&id=7P95CZ", thumb: "/assets/games/t_c46b12186e.jpg", category: "Games" },
  { title: "Nocturne", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/nocturn-auto-1@main/nocturneubg-code-2.svg", thumb: "/assets/games/t_b9fd37178e.jpg", category: "Games" , directOnly: true },
  { title: "Uranium", url: "https://script.google.com/macros/s/AKfycbzQz9WnL48W0kCYKEE_1oowmnObY9yFEQxfvAV3UB57llQjtyEj4lnEBvox_ugVXtoGWA/exec", thumb: "/assets/games/t_4d1dbf0792.jpg", category: "Games" },
  { title: "Velcro", url: "https://script.google.com/macros/s/AKfycbztsJYd44KvwW8ti-I9wQMsLRHBqMX_YYwtoZwJqvdnDGGFUDIiWeLDbFeqJ_YETbxo/exec?id=FGLKH", thumb: "/assets/games/t_9934434c66.jpg", category: "Games" },
  { title: "YukiOS", url: "/game-builds/yukios/index.html", thumb: "/assets/games/t_91c87f55bc.jpg", category: "OS" },
  { title: "PS4 Greg", url: "https://ps4-greg.theropg20.workers.dev/", thumb: "/assets/ps4-banner.png", category: "Games" },
  { title: "Zaka 1", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-1.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true },
  { title: "Zaka 2", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-2.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true },
  { title: "Zaka 3", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-3.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true },
  { title: "Zaka 4", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-4.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true },
  { title: "Zaka 5", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-5.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true },
  { title: "Zaka 6", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-6.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true },
  { title: "Zaka 7", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-7.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true },
  { title: "Zaka 8", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-8.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true },
  { title: "Zaka 9", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-9.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true },
  { title: "Zaka 10", url: "https://cdn.jsdelivr.net/gh/Mtreasur0133-bit/zaka-auto-1@main/zaka-10.svg", thumb: "/assets/games/t_b8f42e72b0.jpg", category: "Zaka" , directOnly: true }
];
