#!/usr/bin/env python3
"""Index the real in-game captures so the library can show them.

tools/real-shots.js boots each local build headless and saves the best stable
frame to assets/games/real/<slug>.<jpg|webp>. This tool walks that folder and
writes src/real-shots.js, the list app.js reads at seed time to swap a
generated cover for the real capture.

Two things it gets right that a plain file listing would not:

  * Every capture is indexed, not just the JPEGs. The grabber saves some games
    as WebP (smaller, same frame), and those files used to sit on disk
    unreferenced because the swap only ever looked for "<slug>.jpg".
  * The extension travels with the slug, so the swap points at the file that
    actually exists instead of guessing.

Run from the repo root:

    python tools/real-shots-index.py            # rewrite src/real-shots.js
    python tools/real-shots-index.py --dry-run  # report only
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REAL_DIR = "assets/games/real"
OUT = "src/real-shots.js"
EXTENSIONS = (".jpg", ".webp")

HEADER = """/* real-shots.js - Real in-game captures for local games.
 *
 * Generated by tools/real-shots-index.py from the files in assets/games/real/
 * (the frames themselves come from tools/real-shots.js). Each slug is the URL
 * stem of a local /ugs/, /mc/ or /gn/ game and the art lives at
 * assets/games/real/<slug>.<ext>. The games seed in app.js swaps generated SVG
 * covers for these captures at load time, so the library shows real art for
 * every game that has it.
 *
 * Rerun the indexer after capturing new frames - do not hand-edit this file.
 */
"""


def collect():
    """slug -> extension, preferring the JPEG when a game has both."""
    found = {}
    folder = os.path.join(ROOT, REAL_DIR)
    for name in sorted(os.listdir(folder)):
        stem, ext = os.path.splitext(name)
        ext = ext.lower()
        if ext not in EXTENSIONS:
            continue
        if stem not in found or (ext == ".jpg" and found[stem] == "webp"):
            found[stem] = ext.lstrip(".")
    return found


def emit(found):
    lines = [HEADER, "window.ChalkRealShots = [\n"]
    for slug in sorted(found, key=str.lower):
        lines.append('  "%s",\n' % slug.replace("\\", "\\\\").replace('"', '\\"'))
    lines.append("];\n")
    webp = {s: e for s, e in found.items() if e != "jpg"}
    lines.append("\n/* Captures saved as WebP instead of JPEG, keyed by slug. A slug\n"
                 "   missing from this map is a .jpg. */\n")
    lines.append("window.ChalkRealShotExt = {\n")
    for slug in sorted(webp, key=str.lower):
        lines.append('  "%s": "webp",\n' % slug.replace("\\", "\\\\").replace('"', '\\"'))
    lines.append("};\n")
    return "".join(lines)


def main():
    found = collect()
    webp = sum(1 for ext in found.values() if ext != "jpg")
    print("captures indexed: %d (%d jpg, %d webp)" % (len(found), len(found) - webp, webp))
    if "--dry-run" in sys.argv:
        print("dry run: nothing written")
        return
    with open(os.path.join(ROOT, OUT), "w", encoding="utf-8", newline="") as handle:
        handle.write(emit(found))
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
