/* Imported from the Noah's Calculus Tutor catalog (424-entry collection).
 * Game pages: /ugs/noah/*.html (local shells; most load builds from jsDelivr).
 * Thumbnails: /assets/games/noah/* (real cover art shipped with the source repo).
 * Regenerate with: node scripts/import-noah.mjs */
(function () {
  "use strict";

  window.ChalkNoahGames = [
  { title: "Trombone Champ", category: "Rhythm", desc: "A rhythm game where you play the trombone by sliding your mouse to match musical notes.", url: "/ugs/noah/472.html", thumb: "/assets/games/noah/472.jpg" },
  { title: "Kick the Buddy", category: "Action", desc: "Explode, destroy, fire, shoot, smash, freeze, and toss the buddy with an endless arsenal!", url: "/ugs/noah/470.html", thumb: "/assets/games/noah/470.jpg" },
  { title: "La Madriguera", category: "Arcade", desc: "A Spanish indie game about a lazy bear trying to reach for his honey.", url: "/ugs/noah/468.html", thumb: "/assets/games/noah/468.jpg" },
  { title: "FNF vs Shucks V2", category: "Rhythm", desc: "uhhh some FNF mod with bad jeffy guy", url: "/ugs/noah/464.html", thumb: "/assets/games/noah/464.jpg" },
  { title: "Cup Head", category: "Action", desc: "Fight a series of monsters to break your deal with the devil", url: "/ugs/noah/266.html", thumb: "/assets/games/noah/188.jpg" },
  { title: "Totally Accurate Battle Simulator", category: "Simulation", desc: "A humorous physics-based battle game where you command a squad of soldiers in various scenarios.", url: "/ugs/noah/462.html", thumb: "/assets/games/noah/462.jpg" },
  { title: "Animal Crossing", category: "Simulation", desc: "A life simulation game where you can live on a deserted island.", url: "/ugs/noah/459.html", thumb: "/assets/games/noah/459.jpg" },
  { title: "Who's Your Daddy?", category: "Arcade", desc: "A comedic co-op game where you play as a confused father is trying to save his son from certain death.", url: "/ugs/noah/440.html", thumb: "/assets/games/noah/440.jpg" },
  { title: "Minecraft 1.12.1", category: "Minecraft", desc: "The World of Color update: new blocks and more color for builders.", url: "/ugs/noah/164.html", thumb: "/assets/games/noah/291.jpg" },
  { title: "CheeseRoll", category: "Racing", desc: "A physics-based racing game where you chase a giant wheel of cheese down a steep, treacherous hill.", url: "/ugs/noah/414.html", thumb: "/assets/games/noah/414.jpg" },
  { title: "Cleggy Car", category: "Racing", desc: "Navigate a wobbly, physics-driven car through challenging terrain in this quirky driving simulator.", url: "/ugs/noah/415.html", thumb: "/assets/games/noah/415.jpg" },
  { title: "Hobo 2: Prison Brawl", category: "Action", desc: "Locked up but not backing down. Fight your way through prison in the second installment of the series.", url: "/ugs/noah/437.html", thumb: "/assets/games/noah/425.jpg" },
  { title: "Scary Shawarma", category: "Horror", desc: "A horror-themed food stand simulation. Serve customers while surviving strange and spooky events.", url: "/ugs/noah/430.html", thumb: "/assets/games/noah/430.jpg" },
  { title: "Brawl Simulator", category: "Simulation", desc: "Open boxes, collect brawlers, and upgrade your team in this fan-made strategic simulator.", url: "/ugs/noah/434.html", thumb: "/assets/games/noah/434.jpg" },
  { title: "Lumines II", category: "Rhythm", desc: "A stylish rhythm-puzzle game where you match colored blocks to the beat of an evolving soundtrack.", url: "/ugs/noah/408.html", thumb: "/assets/games/noah/408.jpg" },
  { title: "Madness Combat: Project Nexus", category: "RPG", desc: "Experience the brutal action of the Madness Combat universe in this intense fan-made Undertale-style duel.", url: "/ugs/noah/411.html", thumb: "/assets/games/noah/411.jpg" },
  { title: "Customer Support", category: "Simulation", desc: "A quirky and tense simulation where you must manage increasingly strange requests while keeping your cool.", url: "/ugs/noah/383.html", thumb: "/assets/games/noah/383.jpg" },
  { title: "Fireboy and Watergirl: Forest Temple", category: "Puzzle", desc: "The original cooperative puzzle platformer. Work together to navigate the Forest Temple and collect all the gems.", url: "/ugs/noah/385.html", thumb: "/assets/games/noah/385.jpg" },
  { title: "Earn to Die", category: "Racing", desc: "Drive your way through a zombie apocalypse, upgrading your car to mow down the undead and reach safety.", url: "/ugs/noah/378.html", thumb: "/assets/games/noah/378.jpg" },
  { title: "Earn to Die 2", category: "Racing", desc: "The massive sequel featuring a new story mode, destructible vehicles, and even more zombies to smash through.", url: "/ugs/noah/379.html", thumb: "/assets/games/noah/379.jpg" },
  { title: "Gacha Life", category: "Simulation", desc: "Create your own anime-style characters and dress them up in your favorite fashion outfits!", url: "/ugs/noah/375.html", thumb: "/assets/games/noah/375.jpg" },
  { title: "Gacha Verse", category: "Simulation", desc: "The sequel to Gacha World. Customize your heroes, battle in the arena, and explore a vast new world.", url: "/ugs/noah/376.html", thumb: "/assets/games/noah/376.jpg" },
  { title: "Tung Sahur Horror", category: "Horror", desc: "A terrifying stealth-horror game based on the tradition of waking people for Sahur. Don't let the entities catch you.", url: "/ugs/noah/377.html", thumb: "/assets/games/noah/377.jpg" },
  { title: "Horror Tale", category: "Horror", desc: "A scary adventure game where you must solve puzzles and save children from a mysterious masked kidnapper.", url: "/ugs/noah/373.html", thumb: "/assets/games/noah/373.jpg" },
  { title: "Little Big Planet", category: "Arcade", desc: "A whimsical world of platforming and creativity where you can play, create, and share your own levels while playing as sackboy", url: "/ugs/noah/351.html", thumb: "/assets/games/noah/351.jpg" },
  { title: "The Binding of Isaac: Rebirth", category: "RPG", desc: "A randomly generated action RPG shooter with heavy rogue-like elements. Follow Isaac on his journey to escape his mother", url: "/ugs/noah/350.html", thumb: "/assets/games/noah/350.jpg" },
  { title: "Littlest Pet Shop City Friends", category: "Simulation", desc: "Explore the city, play fun mini-games, and collect adorable pets in this charming adventure", url: "/ugs/noah/348.html", thumb: "/assets/games/noah/349.jpg" },
  { title: "Cloverpit", category: "Action", desc: "A dark gambling rogue-lite. Beat the slot machine, pay your debts, and escape the pit", url: "/ugs/noah/342.html", thumb: "/assets/games/noah/343.jpg" },
  { title: "Dad 'n Me", category: "Arcade", desc: "A classic side-scrolling beat 'em up where you play as a purple bully causing chaos at the park", url: "/ugs/noah/345.html", thumb: "/assets/games/noah/346.jpg" },
  { title: "Five Nights at Candy's 1", category: "Horror", desc: "A popular fan-made horror game inspired by FNAF, featuring Candy the Cat and his robotic friends", url: "/ugs/noah/346.html", thumb: "/assets/games/noah/347.jpg" },
  { title: "Deltarune Chapters 3 & 4", category: "RPG", desc: "A journey continues in the latest chapters of Deltarun, explore new areas and face new challenges with Kris and friends", url: "/ugs/noah/340.html", thumb: "/assets/games/noah/341.jpg" },
  { title: "Hamtaro: Ham-Ham Heartbreak", category: "Arcade", desc: "Help Hamtaro and Bijou reunite Ham-Hams and repair broken hearts in this charming adventure", url: "/ugs/noah/336.html", thumb: "/assets/games/noah/337.jpg" },
  { title: "Beeswarm Simulator (html version)", category: "Simulation", desc: "That one roblox game where you collect bees as slaves, except someone remade it in html", url: "/ugs/noah/312.html", thumb: "/assets/games/noah/335.jpg" },
  { title: "The Man FROM The Window", category: "Horror", desc: "A horror experience where you must hide from a mysterious presence lurking outside your home", url: "/ugs/noah/293.html", thumb: "/assets/games/noah/315.jpg" },
  { title: "Kirby Soft & Wet", category: "RPG", desc: "A Kirby adventure featuring classic copy abilities and physics-based platforming challenges", url: "/ugs/noah/292.html", thumb: "/assets/games/noah/314.jpg" },
  { title: "Stick War Legacy", category: "Action", desc: "A popular mobile strategy game where you lead armies of stick figures, managing resources like gold to build units", url: "/ugs/noah/171.html", thumb: "/assets/games/noah/293.jpg" },
  { title: "Five Nights at Winstons", category: "Horror", desc: "Office-themed horror game inspired by FNAF with quirky animatronics and survival mechanics", url: "/ugs/noah/157.html", thumb: "/assets/games/noah/285.jpg" },
  { title: "Minesweeper Classic", category: "Puzzle", desc: "A single-player logic puzzle where you clear a grid of hidden mines by revealing tiles", url: "/ugs/noah/162.html", thumb: "/assets/games/noah/290.jpg" },
  { title: "Slendy Tubbies", category: "Horror", desc: "A popular indie horror game series blending the cute Teletubbies with the terrifying mechanics of Slender", url: "/ugs/noah/273.html", thumb: "/assets/games/noah/281.jpg" },
  { title: "Flying Gorilla", category: "Retro", desc: "A free, addictive 3D mobile arcade runner where players control a flying gorilla", url: "/ugs/noah/271.html", thumb: "/assets/games/noah/279.jpg" },
  { title: "Eat The Rich", category: "Simulation", desc: "An Incremental Black Friday Simulator where you gather a mob and score massive savings!", url: "/ugs/noah/270.html", thumb: "/assets/games/noah/278.jpg" },
  { title: "Grand Thef Auto Vice City", category: "Racing", desc: "An 80s-inspired open-world crime saga. Drive fast, build a criminal empire, and shoot your way to the top in a neon-soaked city", url: "/ugs/noah/149.html", thumb: "/assets/games/noah/272.jpg" },
  { title: "Heretic", category: "Retro", desc: "A dark medieval first-person shooter. Wield powerful magic and weapons to battle hordes of dark fantasy creatures.", url: "/ugs/noah/150.html", thumb: "/assets/games/noah/273.jpg" },
  { title: "Oneshot", category: "Puzzle", desc: "A unique narrative puzzle game. Guide a child through a strange, dying world, forming a unique bond that transcends the game itself", url: "/ugs/noah/152.html", thumb: "/assets/games/noah/275.jpg" },
  { title: "FNF Rewrite", category: "Rhythm", desc: "A deceptive Friday Night Funkin' mod featuring the EXE character Rewrite. Starts as a typical horror mod before revealing a twist, with only two intense songs", url: "/ugs/noah/154.html", thumb: "/assets/games/noah/277.jpg" },
  { title: "Call of Duty: World at War", category: "Action", desc: "Intense DS version of the WWII FPS", url: "/ugs/noah/130.html", thumb: "/assets/games/noah/258.jpg" },
  { title: "Call of Duty 4: Modern Warfare", category: "Action", desc: "DS Version of the modern military shooter", url: "/ugs/noah/129.html", thumb: "/assets/games/noah/259.jpg" },
  { title: "Ace Attorny", category: "RPG", desc: "Courtroom drama adventure where you investigate crimes and defend clients with evidence and logic", url: "/ugs/noah/126.html", thumb: "/assets/games/noah/250.jpg" },
  { title: "FNF Agoti", category: "Rhythm", desc: "Friday Night Funkin' mod featuring the popular OC character Agoti with original tracks", url: "/ugs/noah/125.html", thumb: "/assets/games/noah/249.jpg" },
  { title: "FNF Black Betrayal", category: "Rhythm", desc: "FNF mod based on the Among Us mod with the black imposter going crazy", url: "/ugs/noah/124.html", thumb: "/assets/games/noah/248.jpg" },
  { title: "FNF B-Side", category: "Rhythm", desc: "FNF mod featuring remixed B-side versions of original tracks with new visuals", url: "/ugs/noah/123.html", thumb: "/assets/games/noah/247.jpg" },
  { title: "FNF Camellia", category: "Rhythm", desc: "Challenging FNF mod featuring high-BPM tracks from artist Camellia", url: "/ugs/noah/122.html", thumb: "/assets/games/noah/246.jpg" },
  { title: "FNF Impostor V4", category: "Rhythm", desc: "Among Us themed FNF mod with sus rhythms and impostor gameplay", url: "/ugs/noah/121.html", thumb: "/assets/games/noah/245.jpg" },
  { title: "FNF Indie Cross", category: "Rhythm", desc: "Crossover FNF mod featuring characters from popular indie games", url: "/ugs/noah/120.html", thumb: "/assets/games/noah/244.jpg" },
  { title: "FNF Kapi", category: "Rhythm", desc: "FNF mod featuring the arcade-loving cat character Kapi with arcade-style tracks", url: "/ugs/noah/119.html", thumb: "/assets/games/noah/243.jpg" },
  { title: "FNF Mario Madness", category: "Rhythm", desc: "Mario-themed FNF mod with madness-induced versions of classic characters", url: "/ugs/noah/118.html", thumb: "/assets/games/noah/242.jpg" },
  { title: "FNF Pibby Apocalypse", category: "Rhythm", desc: "FNF mod based on the Pibby corruption concept with glitch-themed horror", url: "/ugs/noah/117.html", thumb: "/assets/games/noah/241.jpg" },
  { title: "FNF Shaggy X Matt", category: "Rhythm", desc: "FNF crossover mod featuring Shaggy and Matt from Wii Sports in musical battles", url: "/ugs/noah/116.html", thumb: "/assets/games/noah/240.jpg" },
  { title: "FNF Sonic.exe", category: "Rhythm", desc: "Horror-themed FNF mod based on the Sonic.exe creepypasta with intense rhythms", url: "/ugs/noah/115.html", thumb: "/assets/games/noah/239.jpg" },
  { title: "FNF Garcello", category: "Rhythm", desc: "Emotional FNF mod featuring the character Garcello with soulful tracks", url: "/ugs/noah/114.html", thumb: "/assets/games/noah/238.jpg" },
  { title: "FNF Hit Single", category: "Rhythm", desc: "FNF mod with that blue singing guy that everyone likes", url: "/ugs/noah/113.html", thumb: "/assets/games/noah/237.jpg" },
  { title: "Achillies 2", category: "Action", desc: "Sequel to the action-packed Achillies game with enhanced combat and story", url: "/ugs/noah/112.html", thumb: "/assets/games/noah/236.jpg" },
  { title: "Russian Counter Strike", category: "Action", desc: "Counter-Strike inspired tactical shooter with Russian military themes", url: "/ugs/noah/111.html", thumb: "/assets/games/noah/235.jpg" },
  { title: "Lego Batman 2", category: "Action", desc: "LEGO action-adventure featuring Batman and DC superheroes in Gotham City", url: "/ugs/noah/108.html", thumb: "/assets/games/noah/232.jpg" },
  { title: "Lego Starwars Complete Saga", category: "Action", desc: "Complete LEGO Star Wars experience covering all six episodes with humor and action", url: "/ugs/noah/107.html", thumb: "/assets/games/noah/231.jpg" },
  { title: "Madness Interactive", category: "Action", desc: "Fast-paced stick figure combat game with intense action and ragdoll physics", url: "/ugs/noah/106.html", thumb: "/assets/games/noah/230.jpg" },
  { title: "Tony Hawks Pro Skater", category: "Arcade", desc: "Classic skateboarding game with trick combos, iconic skaters, and great soundtrack", url: "/ugs/noah/105.html", thumb: "/assets/games/noah/229.jpg" },
  { title: "Resident Evil 3", category: "Horror", desc: "Survival horror game featuring Jill Valentine escaping Nemesis in Raccoon City", url: "/ugs/noah/103.html", thumb: "/assets/games/noah/227.jpg" },
  { title: "Strange Rope Police", category: "Arcade", desc: "Physics-based game with rope mechanics and law enforcement themes", url: "/ugs/noah/100.html", thumb: "/assets/games/noah/224.jpg" },
  { title: "Street Fighter III", category: "Simulation", desc: "Classic fighting game known for parry system and competitive gameplay", url: "/ugs/noah/99.html", thumb: "/assets/games/noah/223.jpg" },
  { title: "Plants Vs Zombies 2", category: "Rhythm", desc: "Defend your lawn with crazy plants against fun-loving zombies across time", url: "/ugs/noah/92.html", thumb: "/assets/games/noah/197.jpg" },
  { title: "Balatro", category: "Arcade", desc: "Build insane poker hands with special Joker cards", url: "/ugs/noah/268.html", thumb: "/assets/games/noah/195.jpg" },
  { title: "Zombotron Reboot", category: "Action", desc: "Action-packed platform shooter with physics-based combat in zombie-infested world", url: "/ugs/noah/94.html", thumb: "/assets/games/noah/218.jpg" },
  { title: "BloodMoney", category: "Horror", desc: "A gritty crime thriller about the consequences of choices in the criminal underworld", url: "/ugs/noah/86.html", thumb: "/assets/games/noah/212.jpg" },
  { title: "Assessment Examination", category: "Arcade", desc: "A comprehensive test covering multiple subjects to evaluate academic progress and knowledge retention", url: "/ugs/noah/84.html", thumb: "/assets/games/noah/210.jpg" },
  { title: "Douche Bag Life", category: "Simulation", desc: "A satirical life simulator where you make terrible choices to become the ultimate bro", url: "/ugs/noah/78.html", thumb: "/assets/games/noah/203.jpg" },
  { title: "Apple Worm", category: "Puzzle", desc: "A retro arcade game where you guide a worm to eat apples and grow longer", url: "/ugs/noah/75.html", thumb: "/assets/games/noah/201.jpg" },
  { title: "Doki Doki Literature Club", category: "Simulation", desc: "A cute dating simulator where you write poems for your crush, but something is terribly wrong", url: "/ugs/noah/73.html", thumb: "/assets/games/noah/199.jpg" },
  { title: "FNAF: Pizza Sim", category: "Horror", desc: "Manage your own pizzeria while surviving animatronic horrors", url: "/ugs/noah/1.html", thumb: "/assets/games/noah/1.jpg" },
  { title: "Smashy Kart", category: "Racing", desc: "High-speed kart racing with demolition derby elements", url: "/ugs/noah/400.html", thumb: "/assets/games/noah/4.jpg" },
  { title: "Tomodachi Life", category: "Simulation", desc: "Life simulation with quirky island characters", url: "/ugs/noah/5.html", thumb: "/assets/games/noah/9.jpg" },
  { title: "Street Fighter II", category: "Retro", desc: "Classic fighting game with special moves", url: "/ugs/noah/261.html", thumb: "/assets/games/noah/13.jpg" },
  { title: "Steal a Brainrot Online", category: "Multiplayer", desc: "Multiplayer game about strategic theft", url: "/ugs/noah/9.html", thumb: "/assets/games/noah/15.jpg" },
  { title: "Quake III", category: "Retro", desc: "Classic arena shooter with fast combat", url: "/ugs/noah/14.html", thumb: "/assets/games/noah/20.jpg" },
  { title: "Clash Royale", category: "Action", desc: "Strategic card-based battles", url: "https://raw.githubusercontent.com/NoahsAmazingTutoringHelp/Noahs-Calculus-Tutor/refs/heads/master/games/andurdingus.html", thumb: "/assets/games/noah/26.jpg" },
  { title: "Binding of Issac WOTL", category: "Action", desc: "Rogue-like dungeon crawler", url: "/ugs/noah/24.html", thumb: "/assets/games/noah/29.jpg" },
  { title: "Triva Crack", category: "Arcade", desc: "Addictive trivia knowledge challenge", url: "/ugs/noah/27.html", thumb: "/assets/games/noah/32.jpg" },
  { title: "Bow Masters", category: "Arcade", desc: "Precision archery physics game", url: "/ugs/noah/28.html", thumb: "/assets/games/noah/33.jpg" },
  { title: "FNAF: World", category: "Horror", desc: "RPG with FNAF characters", url: "/ugs/noah/30.html", thumb: "/assets/games/noah/36.jpg" },
  { title: "Highway Racers 2", category: "Racing", desc: "High-speed racing action", url: "/ugs/noah/32.html", thumb: "/assets/games/noah/38.jpg" },
  { title: "Bounce Masters", category: "Arcade", desc: "Physics bouncing challenges", url: "/ugs/noah/33.html", thumb: "/assets/games/noah/39.jpg" },
  { title: "Slender", category: "Horror", desc: "Horror survival exploration game", url: "/ugs/noah/37.html", thumb: "/assets/games/noah/43.jpg" },
  { title: "Bad Parenting", category: "Simulation", desc: "Dark comedy parenting simulation", url: "/ugs/noah/42.html", thumb: "/assets/games/noah/51.jpg" },
  { title: "Baldis Basics", category: "Horror", desc: "Survival horror educational parody", url: "/ugs/noah/43.html", thumb: "/assets/games/noah/52.jpg" },
  { title: "Super Falling Fred", category: "Arcade", desc: "Endless falling obstacle avoidance", url: "/ugs/noah/256.html", thumb: "/assets/games/noah/59.jpg" },
  { title: "Super Smash Flash 2", category: "Action", desc: "Platform fighting game", url: "/ugs/noah/253.html", thumb: "/assets/games/noah/64.jpg" },
  { title: "Stake Mines", category: "Arcade", desc: "Cryptocurrency mining strategy", url: "/ugs/noah/246.html", thumb: "/assets/games/noah/73.jpg" },
  { title: "8Ball Pool", category: "Sports", desc: "Realistic pool physics game", url: "/ugs/noah/243.html", thumb: "/assets/games/noah/79.jpg" },
  { title: "Apple Shooter", category: "Action", desc: "Precision apple shooting game", url: "/ugs/noah/233.html", thumb: "/assets/games/noah/94.jpg" },
  { title: "Hextrix", category: "Puzzle", desc: "Hexagon-based puzzle game", url: "/ugs/noah/231.html", thumb: "/assets/games/noah/96.jpg" },
  { title: "Hillclimb Racing", category: "Racing", desc: "Physics-based hill climbing", url: "/ugs/noah/226.html", thumb: "/assets/games/noah/104.jpg" },
  { title: "Boxing Live 2", category: "Sports", desc: "Physics-based boxing game", url: "/ugs/noah/223.html", thumb: "/assets/games/noah/107.jpg" },
  { title: "Wheelie Bike 2", category: "Arcade", desc: "Motorcycle stunt game", url: "/ugs/noah/221.html", thumb: "/assets/games/noah/111.jpg" },
  { title: "Stacktris", category: "Puzzle", desc: "Tetris-inspired stacking game", url: "/ugs/noah/214.html", thumb: "/assets/games/noah/123.jpg" },
  { title: "Gun Spin", category: "Action", desc: "Weapon spinning challenge", url: "/ugs/noah/201.html", thumb: "/assets/games/noah/143.jpg" },
  { title: "Thorns and Balloons", category: "Arcade", desc: "Balloon popping game", url: "https://noahsamazingtutoringhelp.github.io/ScienceStudyBuddy/", thumb: "/assets/games/noah/144.jpg" },
  { title: "Friday Night Funkin", category: "Rhythm", desc: "Rhythm music battles", url: "/ugs/noah/195.html", thumb: "/assets/games/noah/151.jpg" },
  { title: "COD Nazi Zombies Portable", category: "Action", desc: "Zombie survival shooter", url: "/ugs/noah/194.html", thumb: "/assets/games/noah/152.jpg" },
  { title: "FNAF", category: "Horror", desc: "Original horror survival", url: "/ugs/noah/166.html", thumb: "/assets/games/noah/164.jpg" },
  { title: "Dodge Ball", category: "Arcade", desc: "Dodgeball game I made (pretty fun)", url: "/ugs/noah/401.html", thumb: "/assets/games/noah/171.jpg" },
  { title: "Age of War 2", category: "Action", desc: "Evolution strategy game", url: "/ugs/noah/183.html", thumb: "/assets/games/noah/172.jpg" },
  { title: "Short Life", category: "Racing", desc: "Quick racing challenges", url: "/ugs/noah/174.html", thumb: "/assets/games/noah/185.jpg" }
  ];
})();
