/* real-shots.js - Real in-game captures for local games.
 *
 * Generated by tools/real-shots.js (boots each local build headless and keeps
 * the best stable frame). Each slug is the URL stem of a local /ugs/ (or /mc/)
 * game, and the actual JPEG lives at assets/games/real/<slug>.jpg. The games
 * seed in app.js swaps generated SVG covers for these captures at load time,
 * so the library always shows real art for games that have it.
 */
window.ChalkRealShots = [
  "Helios-Offline (1)", "Minceraft-I-NotMine_V6", "aaindex", "cl2048cupcakes", "cl3dash", "cl60secondssantarun",
  "cl99nightsitf", "clBTD1", "clSINGLEFILE", "clStickmanKingdomclash", "clUltimatecardrivingsimulator", "clallocation",
  "clancientsins", "clballsandbricks", "clbattlekarts", "clben10alienforce", "clben10racing", "clblightborne",
  "clblockcraftparkour", "clblockydemolitionderby", "clbunnyland", "clburgerandfrights", "clcarcrash3", "clcarkingarena",
  "clcarmods", "clcatmariogood", "clchickenscream", "clchickenwar", "clcrazymotorcycle", "clcs1.6",
  "cldeadlydescent", "cldieinthedungeon", "cldoblox", "cldud", "cledyscarsimulator", "clfunnyshooter2",
  "clfunnyshooter22", "clgeometryvibes", "clgolddiggerfrvr", "clgolforbit", "clgrandactionsimulator-ny", "clgravity",
  "clgravitymod", "clgrey-box-testing", "clgrowagarden", "cljailbreakobbbobob", "cljellytruck", "cljellytruckgood",
  "cljetskiracing", "cljsvecx", "clkaratebros", "clknifehit", "clkonkrio", "clkourio",
  "clluckyblocks", "clmadalinstuntcars", "clmadskillsmotocross2", "clminecraftshooter", "clmotox3mm", "clmrracer",
  "clobby-99-will-lose", "clofflineparadise", "cloperius", "cloppositeday", "clpico8", "clpinkbike",
  "clpokered", "clpolytrackalt", "clpuppethockey", "clragdollrunners", "clrocketjump", "clsiloshowdow",
  "clskyrace-3d", "clsnowroad", "clsonicadvance2sp", "clsonicerazor", "clspacecompany", "clspacewarsbattleground",
  "clsprunked", "clstealbrainrot", "clstickmanclash", "clstickmangtacity", "clsuika", "clsuperliquidsoccer",
  "clsupermarioland2", "clsupersmashflash2butdifversion", "clsupitdept", "clsurvevio", "clsushiunroll", "cltaproad",
  "cltrapthecat", "cluckyblockobbyEUOPHRATESRIVER", "clwaverun", "clzumashooter", "codeorg", "eaglercraft_beta_1.0.2"
];